src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 */
class Property
{

    const HEAT = [
        0 => 'Electrique', 
        1 => 'Gaz'
    ];
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Length(min=5, max=255)
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=300)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function getHeatType(): string{

        return self::HEAT[$this->heat];
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getFormattedPrice() : string{
        return number_format($this->price, 0, '', ' ');
    }

    public function getSlug(){
        return $slugify = (new Slugify())->slugify($this->title);
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class,[
                'choices' => $this->getChoices()
            ])
            ->add('city')
            ->add('adress')
            ->add('postal_code')
            ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices(){

        $choices = Property::HEAT;
        $output=[];
        foreach($choices as $k => $v){
            $output[$v] = $k;
        }
        return $output;

    }
}

src/Controller/PropertyController.php
<?php
namespace App\Controller;

use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Property;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;

class PropertyController extends AbstractController{


   private $repository; 
   private $em;

   public function __construct(PropertyRepository $repository, EntityManagerInterface $em)
   {
      $this->repository = $repository;
      $this->em = $em;
   }
   /**
    * @Route("/biens", name="property.index")
    * @return Response
    */

   public function index(PaginatorInterface $paginator, Request $request): Response {

      $search = new PropertySearch();
      $form = $this->createForm(PropertySearchType::class, $search);
      $form->handleRequest($request);

      $properties = $paginator->paginate(
          $this->repository->findAllVisibleQuery($search),
          $request->query->getInt('page', 1), 12
      );
      
      return $this->render('property/index.html.twig', [
         'current_menu' => 'properties',
          'properties' => $properties,
          'form' => $form->createView()
      ]);

   }

   /**
    * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
    * @return Response
    */
   public function show(Property $property, string $slug) : Response {

      $getSlug = $property->getSlug();

      if($getSlug !== $slug){
         return $this->redirectToRoute('property.show', [
            'id' => $property->getId(),
            'slug' => $property->getSlug()
         ], 301);
      }

      return $this->render('property/show.html.twig', [
         'property' => $property,
         'current_menu' => 'properties'
      ]);
   }
}

templates/property/_property.html.twig
<div class="card mb-4">
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}">
                {{ property.title }}
            </a>
        </h5>
        <p class="card-text"> {{ property.surface }} m² - {{ property.city }} ({{ property.postalCode }})</p>
        <div class="text-primary" style="font-size:2rem; font-weight: bold;">
            {{ property.formattedPrice }}
        </div>
    </div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Tous nos biens'%}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
            <div class="form-row align-items-end">
                <div class="col">
                    {{ form_row(form.minSurface) }}
                </div>
                <div class="col">
                    {{ form_row(form.maxPrice) }}
                </div>
                <div class="col">
                    <div class="form-group">
                        <button class="btn btn-primary">Rechercher</button>
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
    <div class="container mt-4">
        <h1>Voir tous nos biens</h1>
       <div class="row">
           {% for property in properties %}
               <div class="col-md-4">
                    {% include 'property/_property.html.twig' %}
               </div>
           {% endfor %}
       </div>

        <div class="pagination">
            {{ knp_pagination_render(properties) }}
        </div>
    </div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}
{% block title property.title %}
{% block body %}

<div class="jumbotron">
    <div class="row">
        <div class="col-md-8">

        </div>
        <div class="col-md-4">
            <h1>{{ property.title }}</h1>
            <h2>{{ property.rooms }} pièces - {{ property.surface }} m2</h2>
            <div class="text-primary" style ="font-size: 4rem;font-weight: bold;">{{ property.formattedPrice }} €</div>
            <a href="#" class="btn btn-primary">Contacter l'agence</a>
        </div>
    </div>
</div>

<div class="container mt-4">

    <p> {{ property.description }}</p>

    <div class="row">
        <div class="col-md-8">
            <h2>Caractéristiques</h2>
            <table class="table table-striped">
                <tr>
                    <td>Surface habitable</td>
                    <td>{{ property.surface }} m2</td>
                </tr>
                <tr>
                    <td>Pièces</td>
                    <td>{{ property.rooms }}</td>
                </tr>
                <tr>
                    <td>Chambre</td>
                    <td>{{ property.bedrooms }}</td>
                </tr>
                <tr>
                    <td>Etage</td>
                    <td>{{ property.floor }}</td>
                </tr>
                <tr>
                    <td>Chauffage</td>
                    <td>{{ property.heatType }}</td>
                </tr>
            </table>
        </div>
        <div class="col-md-4">
            <h2>Spécificités</h2>
        </div>
    </div>
</div>
{% endblock %}